modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="fire_emblem"
version="1.0.0"
displayName="Fire Emblem"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Lore, MCreator"

[[dependencies.fire_emblem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.fire_emblem]]
    modId="hlcl_core"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fire_emblem]]
    modId="curios"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fire_emblem]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

